[data]
task=pretrain
dataset=SN-Eadro
seed=42
if_test=False
sample_rate=5
batch_size=10
valid_batch_size=10
if_shuffle=False
drop_last=False
if_scale=False
normalize_type=0
num_workers=8
if_save_sv=False
val_loss_min=0.038

[model]
model=M3RLStage1
num_nodes=12
num_features=7
# number of templates
num_events=14
log_dim=100
trace_dim=3
hidden_dim=128
emb_dim=128
d_model=512
num_heads=8
dropout=0.3
history_steps=16
label_steps=16
predict_steps=16
strides=16
self_attn=True
if_dynamic_adj=True
if_semantics=True
if_tfidf=True
if_log_feature=True
num_encoder_layers=2
num_decoder_layers=2
embed=fixed
freq=h
n_samples=5
freeze_pretrained=False
# diffusion
forward_steps=50
sample_steps=50
sample_strategy=ddim_multi
beta_schedule=quad
beta_start=0.0001
beta_end=0.5
cache_interval=4
non_uniform=False
pow=1.4
center=15
eta=0.0

# perturb
if_perturb=False
perturb_type=raw_data  # [raw_data, modality_drop, spatiotemporal_mask]
perturb_only_normal_samples=True
# raw log
raw_data_log_list_perturb_sample_rate=0.1
log_perturb_method=delete  # [delete, duplicate]
log_perturb_intensity=0.8
# raw metric or trace
raw_data_scope=mix  # [mix, single]
raw_data_target_modality=metric  # [metrics, traces]
metric_trace_noise_type=gaussian  # [gaussian, uniform, replace_random]
metric_trace_noise_std=0.1
metric_trace_target_dims=random  # [all, random]
metric_trace_num_dims_to_noise=1
# modality_drop
modality_drop_list=logs  # [logs, metrics, traces]
# spatiotemporal_mask
mask_type=spatial  # [spatial, temporal, spatiotemporal]
mask_value=0.0
mask_scope_nodes=random
mask_node_proportion=0.1
mask_node_num_fixed=1
mask_scope_time=random
mask_time_proportion=0.1
mask_time_num_fixed=1
mask_spatiotemporal_proportion=0.05
[train]
if_amp=False
iters_to_accumulate=1
learning_rate=0.0001
weight_decay=0.0001
lr_decay=True
lr_decay_rate=0.995
if_warmup=False
warmup_steps=5000
warmup_lr = 0.00001
epochs=200
print_every=10
save_limit=2
expid=16512
max_grad_norm=1
patience=20
if_wandb=False
valid_epoch_interval=1

[test]
test_batch_size=10

